export const primeraAtencion = {
  idEmprendedor: null,
  telefonoContacto: null,
  fotoPerfil: null,
  correoPersonal: null,
  genero: null,
  direccion: null,
  fechaNacimiento: null,
  departamento: null,
  municipio: null,
  nombres: null,
  nombres: null,
  nombres: null,
  nombres: null,
  nombres: null,
  nombres: null,
  nombres: null,
  nombres: null,
  nombres: null,
  nombres: null,
  nombres: null,
  nombres: null,
  nombres: null,
  nombres: null,
  nombres: null,
};
